[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # As seguintes variáveis de ambiente são necessárias:
  # NEXT_PUBLIC_SUPABASE_URL - URL do projeto Supabase
  # NEXT_PUBLIC_SUPABASE_ANON_KEY - Chave anônima do Supabase

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"] 